required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway",
  "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger",
  "github.com/volatiletech/sqlboiler",
]

[[constraint]]
  name = "github.com/izumin5210/grapi"
  version = "v0.2.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "v1.2.0"
